#include "frmmain.h"

const QString frmMain::sStyleSheet = QString::fromUtf8("/*QWidget {\n"
                     "	font-size: 9pt;\n"
                     "}*/\n"
                     "\n"
                     "QSpinBox, QDoubleSpinBox {\n"
                     "	padding-top: 1px;\n"
                     "	padding-bottom: 1px;\n"
                     "}\n"
                     "\n"
                     "QGroupBox {\n"
                     "}\n"
                     "\n"
                     "QGroupBox:disabled {\n"
                     "	color: palette(shadow);\n"
                     "}\n"
                     "\n"
                     "QGroupBox[overrided=\"true\"] {\n"
                     "	color: red;\n"
                     "}\n"
                     "\n"
                     "QGroupBox[overrided=\"false\"] {\n"
                     "	color: palette(windowtext);\n"
                     "}\n"
                     "\n"
                     "QGroupBox[checkable=\"true\"]::title {\n"
                     "	margin-top: 1px;\n"
                     "}\n"
                     "\n"
                     "QGroupBox[checkable=\"true\"]::indicator {\n"
                     "	padding: 0 -2 -0 2;\n"
                     "	width: 13;\n"
                     "	height: 13;\n"
                     "}\n"
                     "\n"
                     "QGroupBox[checkable=\"true\"]::indicator:checked {	\n"
                     "	image: url(:/images/collapse.png);\n"
                     "}\n"
                     "\n"
                     "QGroupBox[checkable=\"true\"]::indicator:unchecked {	\n"
                     "	image: url(:/images/expand.png);\n"
                     "}\n"
                     "\n"
                     "QFrame#frameManualControlXY,#frameManualControlZ {\n"
                     "	border: 1px solid lightgray;\n"
                     "	border-radius: 4px;\n"
                     "}\n"
                     "\n"
                     "QSplitter::handle {\n"
                     "	background-repeat: no-repeat;\n"
                     "	background-position: center center;\n"
                     "}\n"
                     "\n"
                     "QSpli"
                                         "tter::handle:vertical {\n"
                     "	background-image: url(\":/images/handle_horizontal.png\");\n"
                     "}\n"
                     "/*\n"
                     "QSplitter::handle:horizontal {\n"
                     "	background-image: url(\":/images/handle_vertical.png\");\n"
                     "}\n"
                     "*/\n"
                     "QTableView {\n"
                     "	selection-background-color: #cdcdff;\n"
                     "	selection-color: rgb(0, 0, 0);\n"
                     "}\n"
                     "\n"
                     "QSlider::horizontal {\n"
                     "	padding-top: 1px;\n"
                     "	padding-bottom: 1px;\n"
                     "}\n"
                     "\n"
                     "QSlider::groove:horizontal {\n"
                     "    border: 1px solid #999999;\n"
                     "    height: 2px; \n"
                     "    background: #8f8f91;\n"
                     "    margin: 2px 0;\n"
                     "}\n"
                     "\n"
                     "QSlider::handle:horizontal {	\n"
                     "	background-image: url(:/images/handle2s.png);\n"
                     "    border: 0px;\n"
                     "    width: 16px;\n"
                     "    margin: -7px 0; \n"
                     "}\n"
                     "\n"
                     "QSlider::handle:horizontal:hover {\n"
                     "	background-image: url(:/images/handle2sh.png);\n"
                     "}\n"
                     "\n"
                     "/*QSlider::sub-page:horizontal {\n"
                     "    background: red;\n"
                     "	margin: 1px 0;\n"
                     "}*/");
